GET http://localhost:8080/api/popular HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/api/search?keyword=camera HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/api/products HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/employee HTTP/1.1
Content-Type: application/json

{
    "birthDate":"1863-01-03",
    "firstName": "Some Old",
    "lastName": "Guy with a wig",
    "gender":"M",
    "hireDate":"1890-05-03"
}

###

DELETE http://localhost:8080/employee HTTP/1.1
Content-Type: application/json

{
    "empNo":500004
}

###

PUT http://localhost:8080/ HTTP/1.1
Content-Type: application/json


###